### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by dhanush281** [Project-Mist-OS/maintainership#1]
## Device you want to apply for
```
device : poco m6 pro 5g and codename : sky 
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
unofficial pixelage
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
``
Years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username

Your Telegram username
@solocaptainblaze

## Ping Us On Telegram For Fast Process...

**Comment by Hansraj76** [comment]
Hope you great luck. Be supportive always💛💛
